-- Cloudflare D1 SQL: legal_actions table
CREATE TABLE IF NOT EXISTS legal_actions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  court_type TEXT NOT NULL,
  stage TEXT NOT NULL,
  action_name TEXT NOT NULL,
  responsible TEXT,
  deadline TEXT,
  deadline_from TEXT,
  legal_source TEXT,
  practical_notes TEXT
);

CREATE TABLE IF NOT EXISTS case_suggested_actions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id TEXT NOT NULL,
  case_id TEXT NOT NULL,
  document_name TEXT,
  court_type TEXT,
  suggested_action TEXT,
  deadline TEXT,
  legal_source TEXT,
  confidence TEXT,
  reasoning TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב א'' - פתיחת ההליך וכתבי הטענות', 'הגשת כתב תביעה (כותרת, עיקר טענות, טיעון עובדתי + נספחים, חוות דעת רפואית וייפוי כוח)', 'התובע', 'פותח את ההליך', '-', 'תק'' 9-15', 'מגבלות היקף: חלק שני עד 4 עמ'' וחלק שלישי עד 7 עמ'' בשלום (6 ו-9 במחוזי)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב א'' - פתיחת ההליך וכתבי הטענות', 'המצאת כתב התביעה וההזמנה לדין', 'התובע', 'בלא דיחוי', 'ממועד ההגשה', 'תק'' 158-163', 'כתב תביעה יומצא בדואר רשום או במסירה אישית בלבד, זולת בהסכמה בכתב (תק'' 162)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב א'' - פתיחת ההליך וכתבי הטענות', 'הגשת כתב הגנה', 'הנתבע', '60 ימים; רשלנות רפואית - 120 ימים', 'ממועד המצאת כתב התביעה לנתבע', 'תק'' 9(ב)', 'אי-הגשה חושפת לפסק דין בהעדר הגנה (תק'' 130); טענות מקדמיות חובה לפרט בכתב ההגנה (תק'' 28)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב א'' - פתיחת ההליך וכתבי הטענות', 'תביעה שכנגד', 'הנתבע', 'יחד עם כתב ההגנה', 'במועד הגשת כתב ההגנה', 'תק'' 21', 'דינה כדין כתב תביעה; אינה תלויה בתביעה העיקרית');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב א'' - פתיחת ההליך וכתבי הטענות', 'הודעה לצד שלישי', 'הנתבע', 'בתוך המועד להגשת כתב ההגנה', 'ממועד המצאת כתב התביעה', 'תק'' 22, 23(ב)', 'כתב הגנה של צד שלישי - 60 ימים מהמצאת ההודעה (תק'' 23(ד))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב א'' - פתיחת ההליך וכתבי הטענות', 'כתב תשובה (רשות)', 'התובע', '14 ימים', 'מיום שהומצא כתב ההגנה', 'תק'' 18(א)', 'עד 3 עמודים; לא יכלול נימוק תביעה חדש');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב א'' - פתיחת ההליך וכתבי הטענות', 'ציון המועד האחרון להגשה בכותרת כל כתב טענות', 'כל עורך דין', 'בכל הגשה', '-', 'תק'' 30', 'כולל מועד ההמצאה של המסמך שמשיבים לו');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב א'' - פתיחת ההליך וכתבי הטענות', 'המצאת העתק לצד שכנגד', 'עורך הדין המגיש', 'בלא דיחוי ועד 3 ימים', 'ממועד ההמצאה לבית המשפט', 'תק'' 160', 'בין עורכי דין - בדוא"ל שבכותרת, בכפוף לוידוא קבלה (תק'' 161(1)(ג))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ב'' - דיון מקדמי ופגישת מהו"ת', 'דיון מקדמי בין בעלי הדין (מיוצגים בלבד)', 'בעלי הדין ובאי כוחם', 'בתוך 30 ימים', 'ממועד המצאת כתב הטענות האחרון', 'תק'' 34-35', 'ליבון פלוגתות, גילוי הדדי, בחינת מנגנון חלופי; הפרה - הוצאות לאלתר (תק'' 38)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ב'' - דיון מקדמי ופגישת מהו"ת', 'דיווח לבית המשפט על הדיון המקדמי (טופס 4)', 'בעלי הדין', 'עד 14 ימים לפני קדם המשפט הראשון', 'ביחס למועד קדם המשפט', 'תק'' 36', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ב'' - דיון מקדמי ופגישת מהו"ת', 'מינוי מגשר מהו"ת (תביעה מעל 40,000 ש"ח)', 'הממונה', 'עד 20 ימים', 'לאחר הגשת כתב הטענות האחרון', 'תק'' 37(ב)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ב'' - דיון מקדמי ופגישת מהו"ת', 'פגישת מהו"ת והתייצבות', 'בעלי הדין', 'עד 30 ימים', 'ממועד המצאת ההודעה על המינוי', 'תק'' 37(ד)', 'אי-התייצבות - חיוב בהוצאות (תק'' 37(י)); הודעת המגשר לממונה - 14 ימים מהפגישה (37(ו))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ג'' - שאלונים, גילוי ועיון', 'משלוח שאלון (עד 25 שאלות; 50 במחוזי מעל 2.5 מיליון/נזק גוף)', 'כל בעל דין', 'עד 30 ימים', 'מהגשת כתב הטענות האחרון או מתום המועד להגשתו, לפי המוקדם', 'תק'' 56(א)-(ב)', 'מענה בתצהיר - 30 ימים ממסירת השאלון; השלמת ההליך עד 30 ימים לפני קדם המשפט (56(ג))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ג'' - שאלונים, גילוי ועיון', 'החלפת תצהירי גילוי מסמכים הדדיים', 'שני הצדדים', 'עד 30 ימים', 'מהגשת כתב הטענות האחרון', 'תק'' 57', 'אי-גילוי מסמך שולל הגשתו כראיה (תק'' 60(ג))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ג'' - שאלונים, גילוי ועיון', 'השלמת הליכי העיון במסמכים', 'שני הצדדים', 'עד 30 ימים', 'מהגשת כתב הטענות האחרון', 'תק'' 58(א)', 'על חשבון מבקש העיון');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ג'' - שאלונים, גילוי ועיון', 'בקשות גילוי/עיון/מענה לשאלון', 'המבקש', 'במסגרת רשימת הבקשות בלבד', 'לפי מועדי תק'' 49(ג)', 'תק'' 59(א)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ד'' - בקשות ורשימת בקשות', 'בקשות מקדמיות לפי תק'' 49(א) (עיכוב הליכים, צירוף צד, איחוד, תיקון וכו'')', 'המבקש', 'עד 45 ימים', 'ממועד הגשת כתב הטענות האחרון', 'תק'' 49(ב)', 'חריגים: סעד זמני, עדות מוקדמת, פסלות שופט');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ד'' - בקשות ורשימת בקשות', 'פנייה מוקדמת לצד שכנגד על כוונה להגיש בקשה', 'המבקש', 'עד 30 ימים', 'מהשלמת הליכי העיון (תק'' 58(א))', 'תק'' 49(ד)', 'תנאי סף להגשת בקשה או לכללתה ברשימה');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ד'' - בקשות ורשימת בקשות', 'הגשת רשימת הבקשות', 'כל בעל דין', 'עד 20 ימים לפני קדם המשפט, ולפחות 7 ימים אחרי הפנייה לצד שכנגד', 'ביחס לקדם המשפט הראשון', 'תק'' 49(ג), (ה)', 'עד עמוד לכל בקשה; בקשה שלא נכללה - רק ברשות (49(ז)); תשובה לרשימה - 14 ימים (49(ה))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ד'' - בקשות ורשימת בקשות', 'תשובה לבקשה בכתב', 'המשיב', '20 ימים', 'מהמצאת ההחלטה המורה על תשובה', 'תק'' 50(3)', 'בקשה/תשובה עד 5 עמ'' (8 בסעד זמני); תצהיר עד 3 עמ'' (6 בסעד זמני)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ד'' - בקשות ורשימת בקשות', 'פניות בעניינים טכניים (שינוי מועדים)', 'הפונה', 'בצירוף עמדת הצד שכנגד', '-', 'תק'' 55, 175א', 'לציין מועד מבוקש ומספר פניות קודמות');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ה'' - קדם משפט ועדים', 'קביעת קדם משפט', 'בית המשפט', 'לאחר שחלף המועד לכתב ההגנה/התשובה האחרון', 'לפי המאוחר', 'תק'' 61(א)', 'ככלל עד 2 ישיבות בשלום, 3 במחוזי (63(א))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ה'' - קדם משפט ועדים', 'רשימת עדים מטעם התובע', 'התובע', 'עד 30 ימים', 'מהשלמת הליכי העיון', 'תק'' 62(1)', 'פירוט מטרת כל עדות');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ה'' - קדם משפט ועדים', 'רשימת עדים מטעם הנתבע', 'הנתבע', 'עד 20 ימים', 'לאחר רשימת התובע', 'תק'' 62', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ה'' - קדם משפט ועדים', 'קדם משפט מסכם - מועדי הוכחות, אופן העדויות, קציבת חקירות וסיכומים', 'בית המשפט', 'בתום קדם המשפט', '-', 'תק'' 63(ד), 67', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ה'' - קדם משפט ועדים', 'בקשה להזמנת עד באמצעות בית המשפט', 'בעל דין', 'תוך 30 ימים מקביעת מועד הדיון ולא פחות מ-14 ימים לפני הדיון', 'מעת קביעת מועד הדיון', 'תק'' 83(ב)', 'בצירוף התחייבות להוצאות העד (תק'' 84)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ו'' - מומחים', 'חוות דעת רפואית', 'בעל הדין הטוען', 'יחד עם כתב הטענות', '-', 'תק'' 87(א), (ד)', 'בקשת פטור/דחייה - לכל המאוחר עם כתב הטענות');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ו'' - מומחים', 'חוות דעת רפואית נגדית מטעם התובע', 'התובע', '60 ימים', 'מהמצאת חוות הדעת שצורפה לכתב ההגנה', 'תק'' 87(ג)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ו'' - מומחים', 'חוות דעת שאינה רפואה - תובע / נתבע', 'התובע / הנתבע', 'עד 90 ימים / עד 30 ימים', 'לפני המועד לשמיעת ראיות', 'תק'' 87(ה)-(ו)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ו'' - מומחים', 'חוות דעת מומחה בית המשפט', 'המומחה', '60 ימים', 'מיום שנודע לו על המינוי', 'תק'' 91(א)', 'שאלות הבהרה - 14 ימים מקבלת חוות הדעת; מענה - 30 ימים (91(ג))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ו'' - מומחים', 'הודעה על חקירת מומחה בית המשפט', 'בעל דין', 'עד קדם המשפט המסכם', 'ואם חוות הדעת מאוחרת - 45 ימים לפני ההוכחות או 7 ימים מקבלתה, לפי המאוחר', 'תק'' 91(ד)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ז'' - הוכחות, פסק דין וערעור', 'שמיעת ראיות ברצף; סיכומים בעל פה ככלל', 'הצדדים', 'מיד בתום הראיות', '-', 'תק'' 64(ב), 74', 'אי-הגשת סיכומים בכתב במועד - כדין אי-התייצבות');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ז'' - הוכחות, פסק דין וערעור', 'הודעה על הצגת ראיה במדיה אלקטרונית', 'בעל דין', 'עד 3 ימים לפני הדיון', '-', 'תק'' 71', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ז'' - הוכחות, פסק דין וערעור', 'ביטול החלטה במעמד צד אחד', 'בעל הדין שנגדו ניתנה', '30 ימים', 'מהמצאת ההחלטה', 'תק'' 131', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ז'' - הוכחות, פסק דין וערעור', 'תשובה לבקשת פסיקתה', 'הצד שכנגד', '14 ימים', 'מהמצאת הבקשה', 'תק'' 133(ג)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ז'' - הוכחות, פסק דין וערעור', 'ערעור בזכות על פסק דין', 'המערער', '60 ימים', 'מיום ההמצאה', 'תק'' 137(א)', 'בצירוף ערובה לפי התוספת השלישית (תק'' 135)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ז'' - הוכחות, פסק דין וערעור', 'בקשת רשות ערעור על החלטה אחרת', 'המבקש', '30 ימים', 'מיום ההמצאה', 'תק'' 137(א)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ז'' - הוכחות, פסק דין וערעור', 'ערעור שכנגד', 'המשיב', '45 ימים', 'מהמצאת הערעור או ההודעה על הערובה, לפי המאוחר', 'תק'' 137(ב)', 'לא חל על בר"ע (149(5))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ז'' - הוכחות, פסק דין וערעור', 'עיכוב ביצוע', 'המבקש', 'מהערכאה שנתנה את ההחלטה כל עוד לא הוגש ערעור; אחר כך - מערכאת הערעור', '-', 'תק'' 145', 'הגשת ערעור אינה מעכבת ביצוע');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ח'' - מסלולים מיוחדים: דיון מהיר (עד 75,000 ש"ח) ופינוי מושכר', 'דיון מהיר: כתב הגנה', 'הנתבע', '45 ימים', 'מהמצאת כתב התביעה', 'תק'' 80(א)', 'תצהיר אימות ורשימת מסמכים מצורפים לכל כתב טענות (תק'' 79)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ח'' - מסלולים מיוחדים: דיון מהיר (עד 75,000 ש"ח) ופינוי מושכר', 'דיון מהיר: קדם משפט / דיון / פסק דין', 'בית המשפט', 'קדם משפט עד 90 ימים; דיון עד 6 חודשים; פסק דין תוך 14 ימים', 'מכתב ההגנה האחרון / מתום הדיון', 'תק'' 80(ג)-(ד), 82', 'עיקרי טיעון עד 14 ימים לפני הדיון (80(ז)); החלטה בבקשה - 7 ימים (80(ה))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ח'' - מסלולים מיוחדים: דיון מהיר (עד 75,000 ש"ח) ופינוי מושכר', 'פינוי מושכר: כתב הגנה / דיון', 'הנתבע / בית המשפט', 'כתב הגנה 30 ימים; דיון עד 30 ימים', 'מהמצאת כתב התביעה / מכתב ההגנה האחרון', 'תק'' 81(ב), (ה)', 'אין תביעה שכנגד, אין צד שלישי ואין קדם משפט (81(ג)-(ד))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ט'' - סעדים זמניים (עיקרי המועדים)', 'סעד זמני לפני תביעה - הגשת התביעה', 'המבקש', '7 ימים', 'ממתן הצו', 'תק'' 95(ג), 100(3)', 'אי-הגשה - הצו פוקע');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ט'' - סעדים זמניים (עיקרי המועדים)', 'המצאת צו ארעי במעמד צד אחד', 'המבקש', 'עד 3 ימים', 'ממתן הצו', 'תק'' 97(ד)', 'במסירה אישית; דיון במעמד הצדדים - עד 14 ימים (97(ה))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ט'' - סעדים זמניים (עיקרי המועדים)', 'בקשת ביטול עיקול זמני/תפיסת ראיות במעמד צד אחד', 'המשיב/המחזיק', '30 ימים', 'מהמצאת הצו', 'תק'' 97(ו)', 'דיון בביטול - עד 14 ימים; תשובת מחזיק לעיקול - 30 ימים (104(א)); אישור עיקול - 14 ימים (105(א))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('civil', 'שלב ט'' - סעדים זמניים (עיקרי המועדים)', 'עיכוב יציאה מהארץ - תוקף', '-', 'שנה, ניתן להאריך בשנה בכל פעם', 'ממתן הצו', 'תק'' 124(ג)', 'תביעה לחילוט ערובה - 90 ימים מפקיעת הסעד (תק'' 101)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב א'' - לפני התביעה: יישוב סכסוך', 'בקשה ליישוב סכסוך (חובה לפני תביעה בין בני זוג / הורים וילדיהם בענייני סכסוך משפחתי)', 'המבקש', 'תנאי סף להגשת תובענה', '-', 'חוק הסדר התדיינויות, ס'' 3', 'חל גם על תביעות שבסמכות בית הדין השרעי/הרבני; פטור בעניינים שהוחרגו ובסעדים דחופים');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב א'' - לפני התביעה: יישוב סכסוך', 'פגישת מהו"ת ראשונה ביחידת הסיוע', 'יחידת הסיוע והצדדים', 'תיקבע בתוך 20 ימים', 'מהגשת הבקשה ליישוב סכסוך', 'תקנות הסדר התדיינויות, התשע"ו', 'עד 4 פגישות מהו"ת ללא תשלום');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב א'' - לפני התביעה: יישוב סכסוך', 'תקופת עיכוב הליכים', 'הצדדים', '45 ימים (הארכה אפשרית ב-15 ימים)', 'מהגשת הבקשה', 'חוק הסדר התדיינויות, ס'' 3(ה)', 'בתקופה זו אין להגיש תובענה; מותר לבקש סעד זמני/דחוף (ס'' 3(ו))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב א'' - לפני התביעה: יישוב סכסוך', 'זכות קדימה להגשת תובענה', 'מגיש הבקשה', '15 ימים', 'מתום תקופת עיכוב ההליכים', 'חוק הסדר התדיינויות, ס'' 4', 'בתקופה זו רק המבקש רשאי להגיש תובענה לערכאה שיבחר (קביעת מרוץ הסמכויות)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ב'' - כתבי טענות', 'כתב תביעה + הזמנה לדין (טופס 1/2)', 'התובע', 'פותח את ההליך', '-', 'תק'' 11', 'כל עניין בתביעה נפרדת לפי הסיווג שבתק'' 15; תביעה שכנגד/צד ג'' בתיק נפרד מקושר (תק'' 9(ד))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ב'' - כתבי טענות', 'הרצאת פרטים (טופס 3; במזונות - טופס 4)', 'התובע', 'יחד עם כתב התביעה', '-', 'תק'' 12', 'במזונות קטין - פירוט הכנסות 12 חודשים ושווי נכסים; אי-מסירת פרט = הודיה (12(ב)(2))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ב'' - כתבי טענות', 'תצהיר אימות לכל כתב טענות', 'כל בעל דין', 'יחד עם כתב הטענות', '-', 'תק'' 16', 'התצהיר אינו תחליף לחקירה ראשית אלא בהוראה (16(ה))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ב'' - כתבי טענות', 'גילוי מסמכים מוקדם - רשימת מסמכים + העתקים', 'כל בעל דין', 'יחד עם כתב הטענות', '-', 'תק'' 17', 'פרק ט'' לתקסד"א (שאלונים וגילוי) אינו חל; שאלון רק ברשות בית המשפט (17(ג))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ב'' - כתבי טענות', 'כתב הגנה (+ הרצאת פרטים במזונות)', 'הנתבע', '30 ימים', 'מהמצאת כתב התביעה לנתבע', 'תק'' 13(א)', 'שונה מהמועד באזרחי (60 ימים)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ב'' - כתבי טענות', 'כתב טענות נוסף / תביעה שכנגד / הודעת צד שלישי', 'בעל הדין', 'רק ברשות בית המשפט; הגנה שכנגד והגנת צד שלישי - 30 ימים', 'מהמצאת ההודעה', 'תק'' 14', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ג'' - ניהול ההליך', 'דיון מקדמי בין בעלי הדין', 'בעלי הדין המיוצגים', 'בתוך 30 ימים', 'ממועד המצאת כתב הטענות האחרון', 'תק'' 20 + תקסד"א 34-36', 'חל רק בתובענה כספית/רכושית (15(א)(1)) ובענייני ירושה (15(ג))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ג'' - ניהול ההליך', 'ישיבת מהו"ת אזרחית', 'הממונה ובעלי הדין', 'כמועדי תקסד"א 37 (מינוי עד 20 ימים; פגישה עד 30 ימים)', 'מהגשת כתב הטענות האחרון', 'תק'' 21', 'רק בתובענה רכושית/ירושה שהחוק להסדר התדיינויות לא חל עליה');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ג'' - ניהול ההליך', 'רשימת בקשות', 'בעלי הדין', 'כמועדי תקסד"א 49', 'ביחס לקדם המשפט', 'תק'' 18(א)', 'חלה רק על תביעות רכושיות (15(א)(1)) וירושה (15(ג)); בקשת ביניים אחרת - בכתב + תצהיר (18(ב))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ג'' - ניהול ההליך', 'קדם משפט', 'בית המשפט', 'רשאי לוותר על קדם משפט', '-', 'תק'' 22', 'אם ויתר - יורה על סדרי ניהול, רשימת עדים ודיון בבקשות');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ג'' - ניהול ההליך', 'התייצבות אישית של בעלי הדין לכל דיון', 'בעלי הדין', 'בכל דיון, לרבות קדם משפט', '-', 'תק'' 23', 'אי-התייצבות - כדין תקסד"א 75');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ג'' - ניהול ההליך', 'שינוי מועד דיון', 'הפונה', 'לפי תקסד"א 175א', '-', 'תק'' 24', 'במשפחה: מו"מ לפשרה או גישור יכולים להצדיק שינוי מועד, בשונה מהאזרחי');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ד'' - מומחים, מזונות זמניים וסעדים', 'מינוי מומחה מטעם בית המשפט (מרשימת המומחים)', 'בית המשפט', 'המצאת מסמכים למומחה - 14 ימים ממינויו', 'מיום המינוי', 'תק'' 25(א), (ג)', 'חוות דעת מטעם בעל דין - רק לאחר בחינת ס'' 8(ג) לחוק (25(ח))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ד'' - מומחים, מזונות זמניים וסעדים', 'הגשת חוות דעת המומחה', 'המומחה', '45 ימים', 'מיום מינויו', 'תק'' 25(ד)', 'באימוץ - מינוי תוך 15 ימים והארכת הגשה עד 15 ימים בלבד (תק'' 63)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ד'' - מומחים, מזונות זמניים וסעדים', 'שאלות הבהרה ותשובות', 'בעל דין / המומחה', '14 ימים לשאלות; 14 ימים לתשובות', 'מקבלת חוות הדעת / מקבלת השאלות', 'תק'' 25(ה)', 'בקשה מנומקת לחקור את המומחה - 14 ימים מקבלת התשובות (25(ו))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ד'' - מומחים, מזונות זמניים וסעדים', 'בקשה למזונות זמניים', 'התובע', 'עם התביעה או לאחריה', '-', 'תק'' 33', 'תשובת המשיב - 14 ימים (33(ג)); דיון - עד 30 ימים מקבלת התשובה (33(ד))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ד'' - מומחים, מזונות זמניים וסעדים', 'צו עיקול בתביעת מזונות', 'המבקש', 'עד סכום מזונות לשנתיים; פוקע 5 שנים מפסק הדין', '-', 'תק'' 34', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ד'' - מומחים, מזונות זמניים וסעדים', 'עיכוב יציאה מהארץ במזונות / נגד קטין', 'המבקש', 'פטור מערובה (במעמד צד אחד); צו נגד קטין - עד גיל 18 באין הוראה', '-', 'תק'' 32(ג), 35', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ד'' - מומחים, מזונות זמניים וסעדים', 'הפניה ליחידת הסיוע במהלך ההליך', 'בית המשפט', 'עיכוב הליכים ל-30 ימים', 'מההפניה', 'תק'' 37', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ד'' - מומחים, מזונות זמניים וסעדים', 'שמיעת ילד (גיל 6 ומעלה)', 'בית המשפט / יחידת הסיוע', 'ההורים ייצרו קשר עם יחידת הסיוע בתוך שבוע', 'מהחלטת ההפניה (טופס 9)', 'תק'' 49-56', 'דברי הילד חסויים (תק'' 55)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ה'' - ערעור', 'ערעור על פסק דין', 'המערער', '45 ימים', 'מיום שהומצא פסק הדין', 'תק'' 45(א)', 'שונה מהאזרחי (60 ימים); ערובה לפי התוספת השלישית לתקסד"א (תק'' 47)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ה'' - ערעור', 'בקשת רשות ערעור על החלטה אחרת (וכן על החלטת המחוזי בערעור)', 'המבקש', '30 ימים', 'מיום ההמצאה', 'תק'' 45(ב)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ה'' - ערעור', 'ערעור על החלטת רשם / רשם ההוצאה לפועל', 'המערער', '15 ימים', 'מיום שהומצאה ההחלטה', 'תק'' 45(ג)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ה'' - ערעור', 'תשובה בכתב לערעור / לבר"ע / לערעור על רשם', 'המשיב', '45 / 30 / 15 ימים', 'מהמצאת ההחלטה המורה על תשובה', 'תק'' 46', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ו'' - החזרת ילדים חטופים (אמנת האג) - לוח זמנים מיוחד', 'תשובת המשיב לתביעה', 'המשיב', '13 ימים, ולא יאוחר מיומיים לפני הדיון, לפי המוקדם', 'מהמצאת ההודעה על מועד הדיון', 'תק'' 104', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ו'' - החזרת ילדים חטופים (אמנת האג) - לוח זמנים מיוחד', 'הדיון בתביעה / חקירות / חוות דעת מומחה', 'בית המשפט', 'דיון עד 15 ימים; חקירות עד 5 ימים אחרי הדיון; חוות דעת תוך 14 ימים', 'מהגשת התביעה / מהדיון / מהמינוי', 'תק'' 105, 106(ג), 108(ג)', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ו'' - החזרת ילדים חטופים (אמנת האג) - לוח זמנים מיוחד', 'פסק דין', 'בית המשפט', 'עד 6 שבועות', 'מיום הגשת התביעה', 'תק'' 110', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('family', 'שלב ו'' - החזרת ילדים חטופים (אמנת האג) - לוח זמנים מיוחד', 'ערעור; דיון והכרעה בערעור', 'המערער / בית המשפט', 'ערעור - 7 ימים; דיון - עד 10 ימים; הכרעה - עד 30 ימים', 'מהמצאת פסק הדין / מהגשת הערעור', 'תק'' 111', 'הארכת מועדים בפרק זה - רק באישור נשיא (תק'' 117)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב א'' - כתבי טענות', 'הגשת כתב תביעה (ובתביעות שכר/פיצויי פיטורים/קצבה - לפי הטפסים שבתוספת)', 'התובע', 'פותח את ההליך', '-', 'תק'' 2-9', 'אין חובת תצהיר אימות לכתב התביעה');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב א'' - כתבי טענות', 'הגשת כתב הגנה', 'הנתבע', '30 ימים', 'מיום ההוראה אם ניתנה בנוכחותו, או מיום שהומצאה לו', 'תק'' 27(א)', 'תגובה מפורשת לכל טענה - אין די בהכחשה סתמית (תק'' 28); אי-הגשה - פסק דין בהעדר על יסוד כתב התביעה (תק'' 43)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב א'' - כתבי טענות', 'כתב הגנה בתובענות ביטוח לאומי', 'המוסד לביטוח לאומי', '30 ימים', 'מיום שנמסר למוסד העתק כתב התביעה', 'תק'' 33', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב א'' - כתבי טענות', 'תביעה שכנגד / הודעת צד שלישי', 'הנתבע', 'עם כתב ההגנה / ברשות בית הדין', '-', 'התקנות (פרק כתבי הטענות)', 'הודעת צד ג'' טעונה ככלל רשות');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ב'' - הליכים מקדמיים וניהול', 'בקשות ביניים בכתב', 'המבקש', 'תשובה בכתב - 7 ימים', 'מקבלת העתק הבקשה (או מועד ארוך שקבע השופט)', 'התקנות (פרק הבקשות)', 'השופט רשאי לדחות בקשה על אתר או להכריע על יסוד הכתב בלבד');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ב'' - הליכים מקדמיים וניהול', 'גילוי מסמכים, עיון ופרטים נוספים', 'המבקש', 'בצו בית הדין בלבד - אין גילוי אוטומטי', 'לפי החלטת בית הדין/הרשם', 'תק'' 46', 'שונה מהותית מהאזרחי: ההליך מותנה בצו; נהוג להגיש בקשה מנומקת לאחר פנייה מוקדמת לצד שכנגד');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ב'' - הליכים מקדמיים וניהול', 'דיון מוקדם / קדם משפט אצל שופט או רשם', 'בית הדין', 'לפי זימון בית הדין', '-', 'ס'' 18 לחוק; התקנות', 'בדיון המוקדם נקבעים מוסכמות ופלוגתאות, צווי גילוי ותצהירי עדות ראשית');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ב'' - הליכים מקדמיים וניהול', 'תצהירי עדות ראשית', 'הצדדים', 'במועדים שיקבע בית הדין בהחלטה', 'מההחלטה', 'החלטות דיוניות', 'ככלל: תצהירי התובע תחילה ולאחריהם תצהירי הנתבע');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ב'' - הליכים מקדמיים וניהול', 'דיון מהיר (תביעות בסכומים נמוכים)', 'בית הדין', 'מסלול מקוצר', '-', 'ס'' 31 לחוק; התקנות', 'ערעור על פסק דין בדיון מהיר - ברשות בלבד');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ג'' - פסק דין וערעור', 'ערעור בזכות לבית הדין הארצי על פסק דין של בית דין אזורי', 'המערער', '30 ימים', 'מיום השימוע, או מהמצאת פסק הדין אם ניתן בהעדר', 'תק'' 73', 'כשאין הוראת חיקוק אחרת');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ג'' - פסק דין וערעור', 'בקשת רשות ערעור על החלטה אחרת של בית דין אזורי', 'המבקש', '15 ימים', 'מיום מתן ההחלטה בפני המבקש, או מהמצאתה', 'תק'' 74', 'ניתנה רשות - הערעור תוך 30 ימים, או שרואים את הבר"ע ככתב ערעור');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ג'' - פסק דין וערעור', 'ערעור על פסק דין של רשם', 'המערער', '15 ימים', 'מיום מתן פסק הדין או מהיום שהודע לו', 'התקנות (פרק הערעורים)', 'ערעור על פסק דין של רשם בשכר עבודה/קצבה - לבית הדין האזורי');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ג'' - פסק דין וערעור', 'ערעור על החלטה אחרת של רשם', 'המערער', '7 ימים', 'מיום מתן ההחלטה או מהיום שהודעה לו', 'התקנות (פרק הערעורים)', 'מוגש לבית הדין האזורי');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ג'' - פסק דין וערעור', 'ערעור בעניין פסלות שופט', 'המערער', '10 ימים', 'מהיום שהודעה ההחלטה בטענת הפסלות', 'התקנות (פסלות)', 'בצירוף תצהיר; המצאה לצדדים בו ביום');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('labor', 'שלב ג'' - פסק דין וערעור', 'ערעור על פסק דין של בית הדין הארצי', '-', 'אין ערעור; ביקורת בג"ץ בלבד', '-', 'פסיקת בג"ץ (הלכת חטיב)', 'עתירה לבג"ץ בעילות התערבות מצומצמות וללא שיהוי');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב א'' - הגשת העתירה', 'מיצוי הליכים מול הרשות לפני העתירה', 'העותר', 'תנאי סף פסיקתי', '-', 'פסיקת בג"ץ', 'פנייה מוקדמת מתועדת לרשות ומתן זמן סביר לתגובה');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב א'' - הגשת העתירה', 'הגשת עתירה הנתמכת בתצהיר לאימות העובדות', 'העותר', 'ללא שיהוי', 'ממועד היווצרות העילה / הידיעה עליה', 'התקנות + הלכת השיהוי', 'אין מועד סטטוטורי קשיח; שיהוי סובייקטיבי/אובייקטיבי עלול להביא לדחייה על הסף');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב א'' - הגשת העתירה', 'המצאת כל כתב בי-דין לבעלי הדין', 'המגיש', 'בו ביום', 'ביום ההגשה לבית המשפט', 'התקנות', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב א'' - הגשת העתירה', 'דחייה על הסף / קביעת דיון מוקדם', 'בית המשפט', 'רשאי לדחות על אתר בלא תשובה', '-', 'התקנות', 'מותב רשאי לדחות עתירה שאינה מגלה עילה בלא דיון');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ב'' - תגובות וצו על תנאי', 'תגובה מקדמית של משיב שהוזמן לדיון', 'המשיב', 'עד 3 ימים לפחות לפני מועד הדיון', 'ביחס למועד שנקבע לדיון', 'התקנות', 'זולת אם הורה בית המשפט אחרת; בהסכמת המשיב ניתן לדון כאילו ניתן צו על תנאי');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ב'' - תגובות וצו על תנאי', 'צו על תנאי - המצאת עותקי העתירה והתצהירים', 'העותר', 'מיד', 'ממתן הצו', 'התקנות', 'ההמצאה למשיבים נעשית עם הצו באמצעות בית המשפט');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ב'' - תגובות וצו על תנאי', 'תצהיר תשובה לצו על תנאי', 'המשיב', 'בתוך המועד שנקבע בצו', 'ממועד ההמצאה', 'התקנות', 'תצהיר התשובה הוא כתב הטענות המרכזי של הרשות');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ב'' - תגובות וצו על תנאי', 'הודעה על רצון לחקור מצהיר', 'בעל הדין שכנגד', 'עד 14 ימים', 'מתום המועד להגשת תצהיר התשובה לצו על תנאי', 'התקנות', 'חקירת מצהיר - ברשות בית המשפט בלבד; מצהיר שלא התייצב - תצהירו לא ישמש ראיה אלא ברשות');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ב'' - תגובות וצו על תנאי', 'צו ביניים', 'בית המשפט', 'בכל עת', '-', 'התקנות', 'בית המשפט רשאי לתת, לבטל ולשנות צווי ביניים');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ג'' - הדיון וההכרעה', 'עיקרי טיעון', 'בעלי הדין', 'לפני הדיון, במועד שנקבע בתקנות או בהחלטה', 'ביחס למועד הדיון', 'התקנות', 'בדיון - טענה או אסמכתה נוספת רק ברשות, אלא אם הן תשובה לעיקרי הטיעון שכנגד');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ג'' - הדיון וההכרעה', 'סדר הטיעון בדיון לאחר צו על תנאי', 'הצדדים', 'המשיב פותח והעותר משיב', '-', 'התקנות', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ג'' - הדיון וההכרעה', 'פסק דין (צו מוחלט / ביטול הצו על תנאי)', 'בית המשפט', '-', '-', '-', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ג'' - הדיון וההכרעה', 'בקשה לדיון נוסף בפסק דין של העליון', 'בעל דין', '15 ימים', 'מיום מתן פסק הדין', 'ס'' 30 לחוק בתי המשפט; תקנות סדר הדין בדיון נוסף, התשמ"ד-1984', 'בהלכה חדשה, קשה או חשובה בלבד');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('hcj', 'שלב ג'' - הדיון וההכרעה', 'מניין הימים - פגרות', '-', 'פגרה אינה במניין הימים', '-', 'התקנות', 'זולת אם הורה בית המשפט או הרשם אחרת');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב א'' - לפני התביעה ופתיחתה', 'בקשה ליישוב סכסוך - חלה גם לפני תביעה בבית הדין השרעי', 'המבקש', 'תנאי סף בענייני סכסוך משפחתי בין בני זוג / הורים וילדיהם', '-', 'חוק הסדר התדיינויות, התשע"ה-2014, ס'' 2-3', 'ההגדרה ''ערכאה שיפוטית'' כוללת את בתי הדין הדתיים; עיכוב הליכים 45 ימים (+15) וזכות קדימה של 15 ימים, כמפורט בגיליון המשפחה');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב א'' - לפני התביעה ופתיחתה', 'הגשת לאיחת אלדעוא (כתב התביעה) בצירוף אגרה', 'התובע', 'פותח את ההליך', '-', 'חוק הפרוצדורה העות''מאני; תקנות בתי הדין השרעיים (אגרות)', 'פירוט בעלי הדין, העילה והסעד; בענייני פירוק נישואין, מהר, נפקה, חצ''אנה וכיו"ב לפי הדין השרעי (הפיקה החנפית וחוק המשפחה העות''מאני)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב א'' - לפני התביעה ופתיחתה', 'המצאת ההזמנה (תבליע'') לנתבע', 'בית הדין', 'לקראת הישיבה הראשונה', '-', 'חוק הפרוצדורה העות''מאני', 'ההמצאה באמצעות מזכירות בית הדין; נתבע שלא התייצב לאחר המצאה כדין - ניתן לדון בהעדרו');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ב'' - בירור התביעה', 'מענה הנתבע (ג''ואב) וטענות הגנה', 'הנתבע', 'בישיבה הראשונה או במועד שיקצוב הקאדי', 'ממועד הישיבה', 'חוק הפרוצדורה העות''מאני', 'ארכות נתונות לשיקול דעת הקאדי; נוהגי בתי הדין כיום מחייבים לרוב הגשת כתב הגנה בכתב במועד שנקבע בהחלטה');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ב'' - בירור התביעה', 'שלב הראיות: עדים (ביינה), מסמכים ושבועה (יומין)', 'הצדדים', 'לפי קביעת הקאדי בכל ישיבה', '-', 'חוק הפרוצדורה העות''מאני; מג''לת אלאחכאם', 'הכלל: אלביינה עלא אלמדעי ואליומין עלא מן אנכר - נטל הראיה על התובע והשבועה על המכחיש');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ב'' - בירור התביעה', 'מינוי בוררים (חכמין) בתביעות פירוק נישואין בעילת ניזאע ושקאק', 'בית הדין', 'במועדים שיקבע בית הדין; דו"ח הבוררים מוגש לאישור', 'מהחלטת המינוי', 'ס'' 130 לחוק המשפחה העות''מאני', 'הצדדים רשאים להגיש התנגדות מנומקת לדו"ח הבוררים במועד שיקצוב בית הדין; הבוררים פוסקים והקאדי מאשר');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ב'' - בירור התביעה', 'סעדים זמניים (מזונות זמניים, עיכוב יציאה, צווי הגנה)', 'המבקש', 'בכל עת, לפי הצורך', '-', 'חוקי המדינה החלים על בתי הדין הדתיים + נוהלי בתי הדין', 'צווי עיכוב יציאה והגנה - מכוח הדין הישראלי הכללי החל גם על בתי הדין השרעיים');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ג'' - פסק דין, השגות וערעור', 'מתן פסק דין (חכם / אעלאם שרעי)', 'הקאדי', '-', '-', 'חוק הפרוצדורה העות''מאני', 'פסק הדין נערך ונחתם ומומצא לצדדים');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ג'' - פסק דין, השגות וערעור', 'התנגדות (אעתראד'') לפסק דין שניתן במעמד צד אחד', 'הנתבע הנעדר', 'במועד הקבוע בדין ובנוהלי בתי הדין', 'מהמצאת פסק הדין', 'חוק הפרוצדורה העות''מאני; תקנות האגרות (פרט ההתנגדות)', 'קיומו של הליך התנגדות לפסק דין גיאבי מעוגן גם בתקנות האגרות; יש לאמת את המועד העדכני מול מזכירות בית הדין/המנשרים');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ג'' - פסק דין, השגות וערעור', 'ערעור לבית הדין השרעי לערעורים בירושלים', 'המערער', '30 ימים (לפי הנוהל הנוהג; מומלץ לאמת מול המנשר העדכני)', 'ממתן פסק הדין או מהמצאתו', 'חוק הפרוצדורה העות''מאני; מנשרי נשיא בית הדין לערעורים; תקנות האגרות', 'בית הדין לערעורים דן בהרכב שלושה קאדים; קיימת גם בקשת רשות ערעור על ''החלטה אחרת'' (תקנות האגרות)');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ג'' - פסק דין, השגות וערעור', 'ביצוע פסק הדין', 'הזוכה', 'לאחר שהפך חלוט / ניתן לביצוע', '-', 'חוק בתי דין דתיים (כפיית ציות ודרכי דיון), התשט"ז-1956; חוק ההוצאה לפועל', 'מזונות נגבים בהוצאה לפועל או באמצעות המוסד לביטוח לאומי (חוק המזונות (הבטחת תשלום))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'שלב ג'' - פסק דין, השגות וערעור', 'ביקורת בג"ץ על בית הדין', 'הנפגע', 'ללא שיהוי', 'מההחלטה', 'ס'' 15(ד)(4) לחוק יסוד: השפיטה', 'בעילות חריגה מסמכות, פגיעה בצדק הטבעי או סתירה לחוק המחייב את בתי הדין');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('sharia', 'הערה מתודולוגית', 'אופי המועדים בבתי הדין השרעיים', '-', 'רוב המועדים נקבעים בהחלטות הקאדי ובמנשרים, ולא בחקיקה קשיחה', '-', '-', 'להבדיל מהערכאות האזרחיות, סדרי הדין השרעיים מבוססים על הדין העות''מאני ועל נהלים פנימיים עדכניים; לפני הסתמכות על מועד - לאמת מול המנשר/ההחלטה בתיק הקונקרטי');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב א'' - לפני כתב האישום', 'יידוע חשוד בפשע על העברת התיק לתובע (מכתב יידוע)', 'רשות התביעה', 'עם העברת חומר החקירה', '-', 'ס'' 60א(א)', 'בעבירות פשע, בכפוף לחריגים שבסעיף');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב א'' - לפני כתב האישום', 'בקשה מנומקת להימנע מהגשת כתב אישום (שימוע)', 'החשוד', '30 ימים', 'מיום קבלת הודעת היידוע', 'ס'' 60א(ד)', 'התובע רשאי להאריך את המועד; אין להגיש כתב אישום בטרם חלף המועד, ככלל');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב א'' - לפני כתב האישום', 'ערר על סגירת תיק / החלטה שלא להעמיד לדין', 'המתלונן', '30 ימים', 'מיום שנמסרה לו ההודעה על ההחלטה', 'ס'' 64-65', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ב'' - מכתב האישום ועד תחילת המשפט', 'הגשת כתב אישום', 'התובע', '-', '-', 'ס'' 62, 85', 'תוכן כתב האישום ופרטיו לפי ס'' 85');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ב'' - מכתב האישום ועד תחילת המשפט', 'המצאת כתב האישום והזמנה למשפט לנאשם', 'בית המשפט / התביעה', 'זמן מספיק לפני מועד המשפט', '-', 'ס'' 95; תקנות סדר הדין הפלילי', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ב'' - מכתב האישום ועד תחילת המשפט', 'עיון בחומר החקירה והעתקתו', 'הנאשם וסניגורו', 'בכל עת לאחר הגשת כתב האישום', '-', 'ס'' 74', 'בקשה לעיון בחומר שלא הועבר - לבית המשפט שדן באישום; על ההחלטה ניתן לערור (74(ה))');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ב'' - מכתב האישום ועד תחילת המשפט', 'טענות מקדמיות (חוסר סמכות, פגם בכתב האישום, התיישנות, הגנה מן הצדק ועוד)', 'הנאשם', 'בתחילת המשפט, לאחר תחילת ההקראה', '-', 'ס'' 149-151', 'חוסר סמכות עניינית ופגם מהותי ניתן להעלות גם בשלב מאוחר ברשות בית המשפט');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ב'' - מכתב האישום ועד תחילת המשפט', 'מענה לאישום (הודאה / כפירה / טענות עובדתיות)', 'הנאשם', 'לאחר ההקראה ובירור הטענות המקדמיות', '-', 'ס'' 152', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ג'' - המשפט', 'פרשת התביעה', 'התובע', 'לפי קביעת בית המשפט', '-', 'ס'' 156-157', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ג'' - המשפט', 'טענת ''אין להשיב לאשמה''', 'הנאשם', 'בתום פרשת התביעה', '-', 'ס'' 158', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ג'' - המשפט', 'פרשת ההגנה וראיות הזמה', 'הנאשם / התובע', 'לפי קביעת בית המשפט', '-', 'ס'' 159-165', '');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ג'' - המשפט', 'סיכומים, הכרעת דין, ראיות וטיעונים לעונש, גזר דין', 'הצדדים / בית המשפט', 'לפי קביעת בית המשפט', '-', 'ס'' 169, 182, 187-193', 'הכרעת דין מזכה או מרשיעה; גזר הדין לאחר טיעונים לעונש');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ד'' - לאחר פסק הדין', 'בקשה לביטול פסק דין שניתן בהעדר הנאשם', 'הנאשם', '30 ימים', 'מהיום שהומצא לו פסק הדין', 'ס'' 130(ח)', 'בית המשפט יבטל אם הייתה סיבה מוצדקת לאי-ההתייצבות או אם הדבר דרוש למניעת עיוות דין');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ד'' - לאחר פסק הדין', 'ערעור בזכות על פסק דין', 'הנאשם או התובע', '45 ימים', 'מיום מתן פסק הדין; ניתן בהעדר - מיום ההמצאה; ניתנה הכרעה ללא נימוקים - מיום מתן הנימוקים', 'ס'' 199', 'הודעת ערעור מנומקת (ס'' 198); שלום למחוזי, מחוזי לעליון');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ד'' - לאחר פסק הדין', 'ערעור הטעון רשות (גלגול שני)', 'המבקש', 'בקשת רשות ערעור בתוך תקופת הערעור (45 ימים)', 'כאמור לעיל', 'ס'' 199-201', 'רשות ערעור לעליון על פסק דין של מחוזי בערעור');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ד'' - לאחר פסק הדין', 'עיכוב ביצוע עונש', 'הנאשם', 'עם מתן גזר הדין או לאחריו', '-', 'ס'' 87', 'בית המשפט שגזר או ערכאת הערעור רשאים לעכב ביצוע');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ד'' - לאחר פסק הדין', 'משפט חוזר', 'הנידון / היועמ"ש', 'בכל עת', '-', 'ס'' 31 לחוק בתי המשפט', 'בעילות שנקבעו בחוק; נדון בבית המשפט העליון');
INSERT INTO legal_actions (court_type, stage, action_name, responsible, deadline, deadline_from, legal_source, practical_notes) VALUES ('criminal', 'שלב ד'' - לאחר פסק הדין', 'התיישנות עבירות והתיישנות עונשים', '-', 'לפי סוג העבירה והעונש', '-', 'ס'' 9-10', 'תקופות ההתיישנות תוקנו ברפורמה; יש לבדוק את הנוסח העדכני לכל עבירה');